"""empty message

Revision ID: 217092bfa2bc
Revises: 0576d8178e68
Create Date: 2025-10-11 14:51:14.626066

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '217092bfa2bc'
down_revision = '0576d8178e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricedata',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('timeframe', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timestamp', 'timeframe', name='uq_symbol_time_frame')
    )
    op.create_index('idx_price_data_symbol_time', 'pricedata', ['symbol_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_price_data_timeframe', 'pricedata', ['timeframe', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_data_timeframe', table_name='pricedata', postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_price_data_symbol_time', table_name='pricedata', postgresql_ops={'timestamp': 'DESC'})
    op.drop_table('pricedata')
    # ### end Alembic commands ###
