"""create symbols

Revision ID: 547a8e60e106
Revises: af343d6d024f
Create Date: 2025-10-06 11:55:41.773320

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '547a8e60e106'
down_revision = 'af343d6d024f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol',
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('base_asset', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('quote_asset', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('symbol_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_order_size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_order_size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.Column('quantity_precision', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'symbol', name='uq_exchange_symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbol')
    # ### end Alembic commands ###
