"""create api key table

Revision ID: 70ecf60ef89c
Revises: 217092bfa2bc
Create Date: 2025-10-11 16:27:59.443726

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '70ecf60ef89c'
down_revision = '217092bfa2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userapikey',
    sa.Column('exchange_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('encrypted_api_key', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('encrypted_api_secret', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exchange_type', 'is_demo', 'is_active', name='uq_user_exchange_demo_active')
    )
    op.drop_index('idx_price_data_symbol_time', table_name='pricedata')
    op.create_index('idx_price_data_symbol_time', 'pricedata', ['symbol_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_price_data_timeframe', table_name='pricedata')
    op.create_index('idx_price_data_timeframe', 'pricedata', ['timeframe', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_data_timeframe', table_name='pricedata', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_price_data_timeframe', 'pricedata', ['timeframe', sa.text('timestamp DESC')], unique=False)
    op.drop_index('idx_price_data_symbol_time', table_name='pricedata', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_price_data_symbol_time', 'pricedata', ['symbol_id', sa.text('timestamp DESC')], unique=False)
    op.drop_table('userapikey')
    # ### end Alembic commands ###
