"""increase max volume size

Revision ID: 8225c4a7de6f
Revises: 70ecf60ef89c
Create Date: 2025-10-25 08:14:06.332635

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8225c4a7de6f'
down_revision = '70ecf60ef89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricedata', 'volume',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=30, scale=8),
               existing_nullable=False)
    op.alter_column('pricedata', 'quote_volume',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=30, scale=8),
               existing_nullable=True)
    op.drop_index('idx_price_data_symbol_time', table_name='pricedata')
    op.create_index('idx_price_data_symbol_time', 'pricedata', ['symbol_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_price_data_timeframe', table_name='pricedata')
    op.create_index('idx_price_data_timeframe', 'pricedata', ['timeframe', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_data_timeframe', table_name='pricedata', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_price_data_timeframe', 'pricedata', ['timeframe', sa.text('timestamp DESC')], unique=False)
    op.drop_index('idx_price_data_symbol_time', table_name='pricedata', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_price_data_symbol_time', 'pricedata', ['symbol_id', sa.text('timestamp DESC')], unique=False)
    op.alter_column('pricedata', 'quote_volume',
               existing_type=sa.Numeric(precision=30, scale=8),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('pricedata', 'volume',
               existing_type=sa.Numeric(precision=30, scale=8),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###
