"""create realtime_prices table

Revision ID: e6d6b1662d4b
Revises: 9b8db78ecf16
Create Date: 2025-12-09 23:50:08.878236

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e6d6b1662d4b'
down_revision = '9b8db78ecf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realtime_prices',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ask_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('change_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', name='uq_realtime_price_symbol')
    )
    op.drop_index(op.f('idx_price_data_symbol_time'), table_name='pricedata')
    op.create_index('idx_price_data_symbol_time', 'pricedata', ['symbol_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index(op.f('idx_price_data_timeframe'), table_name='pricedata')
    op.create_index('idx_price_data_timeframe', 'pricedata', ['timeframe', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_data_timeframe', table_name='pricedata', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_price_data_timeframe'), 'pricedata', ['timeframe', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_price_data_symbol_time', table_name='pricedata', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_price_data_symbol_time'), 'pricedata', ['symbol_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_table('realtime_prices')
    # ### end Alembic commands ###
