"""strategies

Revision ID: ea251db58f8e
Revises: e6d6b1662d4b
Create Date: 2025-12-24 08:11:12.036647

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea251db58f8e'
down_revision = 'e6d6b1662d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradingstrategy',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('strategy_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategysymbol',
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('allocation_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['tradingstrategy.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'symbol_id', name='uq_strategy_symbol')
    )
    op.drop_index(op.f('idx_price_data_symbol_time'), table_name='pricedata')
    op.create_index('idx_price_data_symbol_time', 'pricedata', ['symbol_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index(op.f('idx_price_data_timeframe'), table_name='pricedata')
    op.create_index('idx_price_data_timeframe', 'pricedata', ['timeframe', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_data_timeframe', table_name='pricedata', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_price_data_timeframe'), 'pricedata', ['timeframe', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_price_data_symbol_time', table_name='pricedata', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_price_data_symbol_time'), 'pricedata', ['symbol_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_table('strategysymbol')
    op.drop_table('tradingstrategy')
    # ### end Alembic commands ###
